/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import main.Global;

/**
 *
 * @author Andres
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        changeInitialDataButton = new javax.swing.JButton();
        openNintendoButton = new javax.swing.JButton();
        openCapcomButton = new javax.swing.JButton();
        openBothButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        changeInitialDataButton.setText("CAMBIAR DATOS INICIALES");
        changeInitialDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeInitialDataButtonActionPerformed(evt);
            }
        });
        getContentPane().add(changeInitialDataButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, 247, 60));

        openNintendoButton.setText("VER SIMULACIÓN DE NINTNEDO");
        openNintendoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openNintendoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(openNintendoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 247, 60));

        openCapcomButton.setText("VER SIMULACIÓN DE CAPCOM");
        openCapcomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openCapcomButtonActionPerformed(evt);
            }
        });
        getContentPane().add(openCapcomButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 247, 60));

        openBothButton.setText("VER SIMULACIÓN DE AMBOS");
        openBothButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBothButtonActionPerformed(evt);
            }
        });
        getContentPane().add(openBothButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 247, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/VS_logo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 310, 350));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/capcomlogo.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 210, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nintendologo.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, 210, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeInitialDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeInitialDataButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeInitialDataButtonActionPerformed

    private void openCapcomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openCapcomButtonActionPerformed
        GUIFunctions.openSim(1);
        Global.mainMenu.setVisible(false);
        
    }//GEN-LAST:event_openCapcomButtonActionPerformed

    private void openBothButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openBothButtonActionPerformed
         GUIFunctions.openSim(2);
         Global.mainMenu.setVisible(false);
    }//GEN-LAST:event_openBothButtonActionPerformed

    private void openNintendoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openNintendoButtonActionPerformed
         GUIFunctions.openSim(0);
         Global.mainMenu.setVisible(false);
    }//GEN-LAST:event_openNintendoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeInitialDataButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton openBothButton;
    private javax.swing.JButton openCapcomButton;
    private javax.swing.JButton openNintendoButton;
    // End of variables declaration//GEN-END:variables
}
