/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Enums.CompanyEnum;
import Rules.CapcomRules;
import Rules.CompanyRules;
import Rules.NintendoRules;
import Store.FileEntity;
import Store.JSONStore;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import main.Global;

/**
 *
 * @author Masa500
 */
public class Settings extends javax.swing.JFrame {
    
    CompanyRules nintendoRules = new NintendoRules();
    CompanyRules capcomRules = new CapcomRules();
    JSONStore storeJSON = new JSONStore();

    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
        
        //Agrega los valores de los JSONs a la ventana
        try {
            FileEntity capcomFile = storeJSON.GetFile(CompanyEnum.Capcom);
            FileEntity nintendoFile = storeJSON.GetFile(CompanyEnum.Nintendo);
            
            capcomSistems.setValue(capcomFile.getSistems());
            capcomSprites.setValue(capcomFile.getSprites());
            capcomLevels.setValue(capcomFile.getLevels());
            capcomNarratives.setValue(capcomFile.getNarratives());
            capcomIntegrators.setValue(capcomFile.getIntegrators());
            capcomDLCs.setValue(capcomFile.getDLCs());
            
            nintendoSistems.setValue(nintendoFile.getSistems());
            nintendoSprites.setValue(nintendoFile.getSprites());
            nintendoLevels.setValue(nintendoFile.getLevels());
            nintendoNarratives.setValue(nintendoFile.getNarratives());
            nintendoIntegrators.setValue(nintendoFile.getIntegrators());
            nintendoDLCs.setValue(nintendoFile.getDLCs());
            
            timeGames.setValue(nintendoFile.getDeadLineDays());
            timeDuration.setValue(nintendoFile.getDurationDay()/1000);
            
            this.repaint();
            
        } catch (IOException ex) {
            Logger.getLogger(Settings.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        vovlerButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        timeGames = new javax.swing.JSpinner();
        capcomSistems = new javax.swing.JSpinner();
        capcomSprites = new javax.swing.JSpinner();
        capcomLevels = new javax.swing.JSpinner();
        capcomNarratives = new javax.swing.JSpinner();
        capcomIntegrators = new javax.swing.JSpinner();
        timeDuration = new javax.swing.JSpinner();
        nintendoSistems = new javax.swing.JSpinner();
        nintendoSprites = new javax.swing.JSpinner();
        nintendoLevels = new javax.swing.JSpinner();
        nintendoNarratives = new javax.swing.JSpinner();
        nintendoDLCs = new javax.swing.JSpinner();
        vovlerButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        capcomDLCs = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        nintendoIntegrators = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vovlerButton.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        vovlerButton.setText("Guardar");
        vovlerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar(evt);
            }
        });
        jPanel1.add(vovlerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 540, 90, 40));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("NINTENDO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 230, 70));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Configuraciones");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 490, 70));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setText("Tiempo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setText("Integradores");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setText("Dias para entrega del juego");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 570, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setText("Sprites");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setText("Niveles");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel8.setText("Narrativas");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel9.setText("Trabajadores");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel10.setText("Sistemas");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel11.setText("Duracion de dias");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel13.setText("DLCs");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel15.setText("Sprites");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel16.setText("Niveles");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, -1, -1));

        jLabel17.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel17.setText("Narrativas");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel18.setText("Trabajadores");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, -1));

        jLabel19.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel19.setText("Sistemas");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, -1, -1));

        jLabel21.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("CAPCOM");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 230, 70));

        timeGames.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tiempoJuegos(evt);
            }
        });
        jPanel1.add(timeGames, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 570, 110, -1));

        capcomSistems.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                capcomSistemasChange(evt);
            }
        });
        jPanel1.add(capcomSistems, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 110, -1));

        capcomSprites.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                capcomSpritesChange(evt);
            }
        });
        jPanel1.add(capcomSprites, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 110, -1));

        capcomLevels.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                capcomNivelesChange(evt);
            }
        });
        jPanel1.add(capcomLevels, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 110, -1));

        capcomNarratives.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                capcomNarrativasChange(evt);
            }
        });
        jPanel1.add(capcomNarratives, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 110, -1));

        capcomIntegrators.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                capcomIntegratorsChange(evt);
            }
        });
        jPanel1.add(capcomIntegrators, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 110, -1));

        timeDuration.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tiempoDias(evt);
            }
        });
        jPanel1.add(timeDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 540, 110, -1));

        nintendoSistems.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nintendoSistemasChange(evt);
            }
        });
        jPanel1.add(nintendoSistems, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 110, -1));

        nintendoSprites.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nintendoSpritesChange(evt);
            }
        });
        jPanel1.add(nintendoSprites, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 110, -1));

        nintendoLevels.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nintendoNivelesChange(evt);
            }
        });
        jPanel1.add(nintendoLevels, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 110, -1));

        nintendoNarratives.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nintendoNarrativasChange(evt);
            }
        });
        jPanel1.add(nintendoNarratives, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 110, -1));

        nintendoDLCs.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nintendoDLCsChange(evt);
            }
        });
        jPanel1.add(nintendoDLCs, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 110, -1));

        vovlerButton1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        vovlerButton1.setText("Volver");
        vovlerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver(evt);
            }
        });
        jPanel1.add(vovlerButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, 40));

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel12.setText("DLCs");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        capcomDLCs.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                capcomDLCsChange(evt);
            }
        });
        jPanel1.add(capcomDLCs, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 110, -1));

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel14.setText("Integradores");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, -1, -1));

        nintendoIntegrators.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nintendoIntegratorsChange(evt);
            }
        });
        jPanel1.add(nintendoIntegrators, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volver(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver
        // TODO add your handling code here:
        this.setVisible(false);
        Global.mainMenu.setVisible(true);
    }//GEN-LAST:event_volver

    /**
     * Realiza el cambio de valor si es mas bajo que 0 o mas alto que los empleados totales de la empresa
     * @param evt 
     */
    private void capcomSistemasChange(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_capcomSistemasChange
        // TODO add your handling code here:
        if((int)this.capcomSistems.getValue() <= 0){
        
            this.capcomSistems.setValue(1);
            this.repaint();
        }
        
        int dif = validateEmployeesNumber(CompanyEnum.Capcom);
        if(dif <0){
        
            this.capcomSistems.setValue(((int)this.capcomSistems.getValue())-dif);
            this.repaint();
        }
    }//GEN-LAST:event_capcomSistemasChange

    /**
     * Realiza el cambio de valor si es mas bajo que 0 o mas alto que los empleados totales de la empresa
     * @param evt 
     */
    private void capcomSpritesChange(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_capcomSpritesChange
        // TODO add your handling code here:
        if((int)this.capcomSprites.getValue() <= 0){
        
            this.capcomSprites.setValue(1);
            this.repaint();
        }
        
        int dif = validateEmployeesNumber(CompanyEnum.Capcom);
        if(dif <0){
        
            this.capcomSprites.setValue(((int)this.capcomSprites.getValue())-dif);
            this.repaint();
        }
    }//GEN-LAST:event_capcomSpritesChange

    /**
     * Realiza el cambio de valor si es mas bajo que 0 o mas alto que los empleados totales de la empresa
     * @param evt 
     */
    private void capcomNivelesChange(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_capcomNivelesChange
        // TODO add your handling code here:
        if((int)this.capcomLevels.getValue() <= 0){
        
            this.capcomLevels.setValue(1);
            this.repaint();
        }
        
        int dif = validateEmployeesNumber(CompanyEnum.Capcom);
        if(dif <0){
        
            this.capcomLevels.setValue(((int)this.capcomLevels.getValue())-dif);
            this.repaint();
        }
    }//GEN-LAST:event_capcomNivelesChange

    /**
     * Realiza el cambio de valor si es mas bajo que 0 o mas alto que los empleados totales de la empresa
     * @param evt 
     */
    private void capcomNarrativasChange(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_capcomNarrativasChange
        // TODO add your handling code here:
        if((int)this.capcomNarratives.getValue() <= 0){
        
            this.capcomNarratives.setValue(1);
            this.repaint();
        }
        
        int dif = validateEmployeesNumber(CompanyEnum.Capcom);
        if(dif <0){
        
            this.capcomNarratives.setValue(((int)this.capcomNarratives.getValue())-dif);
            this.repaint();
        }
    }//GEN-LAST:event_capcomNarrativasChange

    /**
     * Realiza el cambio de valor si es mas bajo que 0 o mas alto que los empleados totales de la empresa
     * @param evt 
     */
    private void capcomIntegratorsChange(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_capcomIntegratorsChange
        // TODO add your handling code here:
        if((int)this.capcomIntegrators.getValue() <= 0){
        
            this.capcomIntegrators.setValue(1);
            this.repaint();
        }
        
        int dif = validateEmployeesNumber(CompanyEnum.Capcom);
        if(dif <0){
        
            this.capcomIntegrators.setValue(((int)this.capcomIntegrators.getValue())-dif);
            this.repaint();
        }
    }//GEN-LAST:event_capcomIntegratorsChange

    /**
     * Realiza el cambio de valor si es mas bajo que 0 o mas alto que los empleados totales de la empresa
     * @param evt 
     */
    private void nintendoSistemasChange(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nintendoSistemasChange
        // TODO add your handling code here:
        if((int)this.nintendoSistems.getValue() <= 0){
        
            this.nintendoSistems.setValue(1);
            this.repaint();
        }
        
        int dif = validateEmployeesNumber(CompanyEnum.Nintendo);
        if(dif <0){
        
            this.nintendoSistems.setValue(((int)this.nintendoSistems.getValue())-dif);
            this.repaint();
        }
    }//GEN-LAST:event_nintendoSistemasChange

    /**
     * Realiza el cambio de valor si es mas bajo que 0 o mas alto que los empleados totales de la empresa
     * @param evt 
     */
    private void nintendoSpritesChange(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nintendoSpritesChange
        // TODO add your handling code here:
        if((int)this.nintendoSprites.getValue() <= 0){
        
            this.nintendoSprites.setValue(1);
            this.repaint();
        }
        
        int dif = validateEmployeesNumber(CompanyEnum.Nintendo);
        if(dif <0){
        
            this.nintendoSprites.setValue(((int)this.nintendoSprites.getValue())-dif);
            this.repaint();
        }
    }//GEN-LAST:event_nintendoSpritesChange

    /**
     * Realiza el cambio de valor si es mas bajo que 0 o mas alto que los empleados totales de la empresa
     * @param evt 
     */
    private void nintendoNivelesChange(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nintendoNivelesChange
        // TODO add your handling code here:
        if((int)this.nintendoLevels.getValue() <= 0){
        
            this.nintendoLevels.setValue(1);
            this.repaint();
        }
        
        int dif = validateEmployeesNumber(CompanyEnum.Nintendo);
        if(dif <0){
        
            this.nintendoLevels.setValue(((int)this.nintendoLevels.getValue())-dif);
            this.repaint();
        }
    }//GEN-LAST:event_nintendoNivelesChange

    /**
     * Realiza el cambio de valor si es mas bajo que 0 o mas alto que los empleados totales de la empresa
     * @param evt 
     */
    private void nintendoNarrativasChange(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nintendoNarrativasChange
        // TODO add your handling code here:
        if((int)this.nintendoNarratives.getValue() <= 0){
        
            this.nintendoNarratives.setValue(1);
            this.repaint();
        }
        
        int dif = validateEmployeesNumber(CompanyEnum.Nintendo);
        if(dif <0){
        
            this.nintendoNarratives.setValue(((int)this.nintendoNarratives.getValue())-dif);
            this.repaint();
        }
    }//GEN-LAST:event_nintendoNarrativasChange

    /**
     * Realiza el cambio de valor si es mas bajo que 0 o mas alto que los empleados totales de la empresa
     * @param evt 
     */
    private void nintendoDLCsChange(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nintendoDLCsChange
        // TODO add your handling code here:
        if((int)this.nintendoDLCs.getValue() <= 0){
        
            this.nintendoDLCs.setValue(1);
            this.repaint();
        }
        
        int dif = validateEmployeesNumber(CompanyEnum.Nintendo);
        if(dif <0){
        
            this.nintendoDLCs.setValue(((int)this.nintendoDLCs.getValue())-dif);
            this.repaint();
        }
    }//GEN-LAST:event_nintendoDLCsChange

    /**
     * Realiza el cambio de valor si es mas bajo que 0 
     * @param evt 
     */
    private void tiempoDias(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tiempoDias
        // TODO add your handling code here:
        if((int)this.timeDuration.getValue() <= 0){
        
            this.timeDuration.setValue(1);
            this.repaint();
        }
    }//GEN-LAST:event_tiempoDias

    /**
     * Realiza el cambio de valor si es mas bajo que 0 
     * @param evt 
     */
    private void tiempoJuegos(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tiempoJuegos
        // TODO add your handling code here:
        if((int)this.timeGames.getValue() <= 0){
        
            this.timeGames.setValue(1);
            this.repaint();
        }
    }//GEN-LAST:event_tiempoJuegos

    /**
     * Realiza el cambio de valor si es mas bajo que 0 o mas alto que los empleados totales de la empresa
     * @param evt 
     */
    private void capcomDLCsChange(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_capcomDLCsChange
        // TODO add your handling code here:
        
        if((int)this.capcomDLCs.getValue() <= 0){
        
            this.capcomDLCs.setValue(1);
            this.repaint();
        }
        
        int dif = validateEmployeesNumber(CompanyEnum.Capcom);
        if(dif <0){
        
            this.capcomDLCs.setValue(((int)this.capcomDLCs.getValue())-dif);
            this.repaint();
        }
    }//GEN-LAST:event_capcomDLCsChange

    /**
     * Realiza el cambio de valor si es mas bajo que 0 o mas alto que los empleados totales de la empresa
     * @param evt 
     */
    private void nintendoIntegratorsChange(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nintendoIntegratorsChange
        // TODO add your handling code here:
        int dif = validateEmployeesNumber(CompanyEnum.Nintendo);
        if(dif <0){
        
            this.nintendoIntegrators.setValue(((int)this.nintendoIntegrators.getValue())-dif);
            this.repaint();
        }
    }//GEN-LAST:event_nintendoIntegratorsChange

    /**
     * Guarda los valores respectivos en los JSONs de cada compañia
     * @param evt 
     */
    private void guardar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar
        try {
            // TODO add your handling code here:
            this.storeJSON.setFile(getFile(CompanyEnum.Capcom), CompanyEnum.Capcom);
            this.storeJSON.setFile(getFile(CompanyEnum.Nintendo), CompanyEnum.Nintendo);
            
            Global.daysBetweenReleases = (int)this.timeGames.getValue();
            Global.daysDuartion = (float) ((int) this.timeDuration.getValue())*1000;
            
            this.setVisible(false);
            Global.mainMenu.setVisible(true);
        
        } catch (IOException ex) {
            Logger.getLogger(Settings.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_guardar

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner capcomDLCs;
    private javax.swing.JSpinner capcomIntegrators;
    private javax.swing.JSpinner capcomLevels;
    private javax.swing.JSpinner capcomNarratives;
    private javax.swing.JSpinner capcomSistems;
    private javax.swing.JSpinner capcomSprites;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner nintendoDLCs;
    private javax.swing.JSpinner nintendoIntegrators;
    private javax.swing.JSpinner nintendoLevels;
    private javax.swing.JSpinner nintendoNarratives;
    private javax.swing.JSpinner nintendoSistems;
    private javax.swing.JSpinner nintendoSprites;
    private javax.swing.JSpinner timeDuration;
    private javax.swing.JSpinner timeGames;
    private javax.swing.JButton vovlerButton;
    private javax.swing.JButton vovlerButton1;
    // End of variables declaration//GEN-END:variables

    private FileEntity getFile(CompanyEnum company) {
        
        switch(company){
            case Nintendo:
                return new FileEntity(((int)this.timeDuration.getValue())*1000,(int)this.timeGames.getValue(),(int)this.nintendoNarratives.getValue(),(int)this.nintendoLevels.getValue(),
                        (int)this.nintendoDLCs.getValue(),(int)this.nintendoSistems.getValue(),(int)this.nintendoSprites.getValue(),(int)this.nintendoIntegrators.getValue());
            case Capcom:
               return new FileEntity(((int)this.timeDuration.getValue())*1000,(int)this.timeGames.getValue(),(int)this.capcomNarratives.getValue(),(int)this.capcomLevels.getValue(),
                        (int)this.capcomDLCs.getValue(),(int)this.capcomSistems.getValue(),(int)this.capcomSprites.getValue(),(int)this.capcomIntegrators.getValue());
            default:
                throw new AssertionError(company.name());
        }
    }
    
    private int validateEmployeesNumber(CompanyEnum company){
        
        int diference =0;
        int max =0;
        int sum = 0;
    
        switch(company){
            case Nintendo:
                max = this.nintendoRules.getEmployees();
                sum = (int)this.nintendoNarratives.getValue()+(int)this.nintendoLevels.getValue()+(int)this.nintendoDLCs.getValue()+(int)this.nintendoSistems.getValue()+
                      (int)this.nintendoSprites.getValue()+(int)this.nintendoIntegrators.getValue();
                
                diference = max - sum;
                break;
            case Capcom:
                max = this.capcomRules.getEmployees();
                sum = (int)this.capcomNarratives.getValue()+(int)this.capcomLevels.getValue()+(int)this.capcomDLCs.getValue()+(int)this.capcomSistems.getValue()+
                      (int)this.capcomSprites.getValue()+(int)this.capcomIntegrators.getValue();
                
                diference = max - sum;
                break;
            default:
                throw new AssertionError(company.name());
        }
        
        return diference;
    }
}
